name: Unit tests

on:
  # Allow running the pipeline manually, and run it always on push to main
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run CItests

    - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: JEST Unit Tests            
          path: reports/jest-junit.xml    # Path to test results
          reporter: jest-junit        # Format of test results
